# Generated by Django 4.2.3 on 2023-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("world", models.CharField(max_length=100)),
                ("is_done", models.BooleanField(default=False)),
                ("history", models.JSONField()),
                ("is_win", models.CharField(max_length=100)),
            ],
        ),
    ]
